### ISSUE TITLE
Add a Heroku button for easy deployment

### ISSUE THREAD

**Issue by dguido** [hazcod/security-slacker#15]
https://devcenter.heroku.com/articles/heroku-button
https://blog.heroku.com/how-to-deploy-your-slack-bots-to-heroku

I like to avoid owning new servers and infrastructure to manage simple applications like slack bots. This application could more than adequately live in a Heroku PaaS. It looks like it already has most if it not all of the attributes of a "12factor" app so this would be pretty easy.

There's a few other good options for automated deployment that Slack recommends too:
https://api.slack.com/docs/hosting

**Comment by hazcod** [comment]
Hi @dguido!  
I am actually building & hosting a container image too, which I guess is what you want?
https://github.com/hazcod/security-slacker/pkgs/container/crowdstrike-spotlight-slacker%2Fcss

If not, let me know and I can investigate a Heroku deploy button by creating a [apps.json](https://github.com/hazcod/security-slacker/pkgs/container/crowdstrike-spotlight-slacker%2Fcss).

**Comment by hazcod** [comment]
I went ahead and added a `Deploy to Heroku` button to the README, but I did not test it yet. Let me know how it goes.
It'll work with settings environment variables prepended with `CSS`. So e.g. when looking at [config.go](https://github.com/hazcod/security-slacker/blob/main/config/config.go)

```
CSS_ SLACK_TOKEN=foo
CSS_ SLACK_SECURITY_USER=foo@company.com
...
```

**Comment by dguido** [comment]
Amazing! I think those custom variables are something you want to define in the app.json:
https://blog.heroku.com/introducing_the_app_json_application_manifest#defining-an-application-setup
https://devcenter.heroku.com/articles/app-json-schema#env

Then, when you click the Deploy to Heroku button, Heroku will prompt you to enter all of the enumerated variables.

**Comment by hazcod** [comment]
I've added the variables in https://github.com/hazcod/security-slacker/commit/aa952a64811f089c7c1921f97690429266a5343c

**Comment by dguido** [comment]
Nice! That should be it. I'll try this as soon as I get a chance!

**Comment by hazcod** [comment]
Alright, feel free to open up a new issue if necessary. Have fun!
